### ISSUE TITLE
Fix mobile styles

### ISSUE THREAD

**Issue by NicholasLYang** [hacknyu/hacknyu-2019#15]
There's some minor bugs with mobile styles on Chrome for iPhone 5/5s. Fix them and test mobile styles for every other phone on the browser dev tools options.

<img width="331" alt="screen shot 2018-12-09 at 4 05 11 pm" src="https://user-images.githubusercontent.com/7357863/49702915-8189ec00-fbcc-11e8-8b9a-93ebcd96d4da.png">
<img width="325" alt="screen shot 2018-12-09 at 4 05 17 pm" src="https://user-images.githubusercontent.com/7357863/49702916-82bb1900-fbcc-11e8-8d34-3b1ba981dd6d.png">
<img width="324" alt="screen shot 2018-12-09 at 4 05 29 pm" src="https://user-images.githubusercontent.com/7357863/49702917-8353af80-fbcc-11e8-8cfc-652ee91171fc.png">

Relevant Components:
- Header.tsx
- HomePage.tsx
- MainApp.tsx

**Comment by stefancherubin** [comment]
Done: https://github.com/hacknyu/hacknyu-2019/pull/61
