### ISSUE TITLE
Finish application form

### ISSUE THREAD

**Issue by NicholasLYang** [hacknyu/hacknyu-2019#34]
Finish the application form with the following:

- undergrad vs grad
- NYU college if NYU
- major(s)
- ethnicity (optional)
- prior experience
- resume upload
- what are you interested in doing or something like that (optional, just for internal use)
- T-shirt size
- Dietary restrictions
- MLH checkboxes (code of conduct, data sharing)

**Comment by stefancherubin** [comment]
Initially done here: https://github.com/hacknyu/hacknyu-2019/pull/35
Cleaned up here: https://github.com/hacknyu/hacknyu-2019/pull/37
Most recent PR has email confirmation: https://github.com/hacknyu/hacknyu-2019/pull/53

@themichaelyang
